services:
  page:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/usr/app
    ports:
      - 3000:3000
    tty: true
    command: [ "/bin/bash" ]
    # command: [ "npm", "run", "start" ]
